### ISSUE TITLE
`{user}` 显示为了QQ号而不是昵称

### ISSUE THREAD

**Issue by kaoet** [dingyi222666/koishi-plugin-better-custom-welcome-message#2]
我用的koishi + better-custom-welcome-message v1.0.9 + NapCat接入了QQ群。

在加群和退群消息中，`{user}`会被显示为此用户的QQ号，而不是文档中写的QQ昵称。

**Comment by kaoet** [comment]
我升级了1.0.10版本，但是bug依旧。

**Comment by dingyi222666** [comment]
经过测试后发现是 NapCat 没有获取到用户的昵称导致的。（也就是使用此方式接入 QQ 没法获取到 QQ 昵称）

你可能需要更换其他接入 QQ 的方式。

**Comment by MliKiowa** [comment]
> 经过测试后发现是 NapCat 没有获取到用户的昵称导致的。（也就是使用此方式接入 QQ 没法获取到 QQ 昵称）
> 
> 你可能需要更换其他接入 QQ 的方式。

请问下调用的是哪个接口
