### ISSUE TITLE
用户进群无提示，但退群有提示

### ISSUE THREAD

**Issue by okatu-loli** [dingyi222666/koishi-plugin-better-custom-welcome-message#4]
我用的koishi + better-custom-welcome-message v1.0.11 + NapCat接入了QQ群。

只有退群会发送消息，入群没有发送消息

如图，反复加群退群测试了很多次

![image](https://github.com/user-attachments/assets/282b13b1-0f60-4802-bd8c-5af4d440a109)

**Comment by dingyi222666** [comment]
你可以使用 LLOneBot 测试一下是否有此问题，如果 LLOneBot 没有此问题，那就是 NapCat 的问题。

**Comment by okatu-loli** [comment]
确认是NapCat的问题，官方已修复
https://github.com/NapNeko/NapCatQQ/commit/5f56c8a7d420f6bfc305b075cd4cc50af8d56f74
