### ISSUE TITLE
onebot 只有进群提示 没有退群提示

### ISSUE THREAD

**Issue by cn1095** [dingyi222666/koishi-plugin-better-custom-welcome-message#6]
使用ntqq  指定了群组ID  只有进群才有@提示    退群没有提示      日志也没有任何报错或提示

**Comment by cn1095** [comment]
我想要退群提示  但是怎么弄都没有提示  也没有任何日志

**Comment by cn1095** [comment]
必须要设置机器人为管理员  退群才有提示吗？

能否缓存所有成员信息进行对比 不需要管理员也能检测到退群

**Comment by dingyi222666** [comment]
如果您使用的是 onebot 平台，请设置为管理员再使用此插件。

**Comment by dingyi222666** [comment]
经过测试，我使用 docker 部署最新 ncqq，koishi（使用 onebot 适配器，非管理员）正常接收到了进群和退群事件。

**Comment by cn1095** [comment]
NTQQ 
![图片](https://github.com/user-attachments/assets/279f968b-7484-435a-8e50-e360fcf874f3)

koshi
![图片](https://github.com/user-attachments/assets/d3c6ce40-513b-4d9d-a597-4269ac1120b9)

onebot
![图片](https://github.com/user-attachments/assets/c6f24442-8c54-4a7c-bcdb-cb78e7eac3df)


插件版本
![图片](https://github.com/user-attachments/assets/4356db96-c2cd-4f00-b52d-9575cf008794)

都是在群晖docker里部署的

反复测试 ： 如果机器人不是管理员就无法接收到退群通知进行推送     设置为管理员才正常
 
最后尝试也使用ncqq  结论还是一样得管理员才行  最后只能管理员解决了

**Comment by dingyi222666** [comment]
![Screenshot_2024-12-18-02-39-05-087_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/9b4ba380-fda7-47ae-b2bd-42cd637e2e7a)

可以看到并没有管理员标签，正常触发了进群和退群通知。

**Comment by cn1095** [comment]
大佬 能否告知我你用的哪个镜像呢？  我用的是koishijs/koishi   lumubiji/ntqq

**Comment by dingyi222666** [comment]
https://github.com/NapNeko/NapCat-Docker

**Comment by cn1095** [comment]
已解决！  感谢大佬！

**Comment by cn1095** [comment]
头像大小可以加选项 640 好像有点大  好像有几个选项可以选择的  我改成40了   好像有40 100 140 240 640 来着

**Comment by dingyi222666** [comment]
> 头像大小可以加选项 640 好像有点大 好像有几个选项可以选择的 我改成40了 好像有40 100 140 240 640 来着

你可以自己替换为相关链接。

> 你也可以填写一个头像 url 的模板，这适用于 onebot(能获取到群成员 ID) 适配器:

> ```
> ![?](https://q.qlogo.cn/headimg_dl?dst_uin={id}&spec=640) 
> ```

**Comment by cn1095** [comment]
是的 我就是改的这里的像素值
